language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - extra-android-m2repository
    - android-23

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

sudo: false

cache:
  directories:
  - $HOME/.m2